version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    privileged: true
    environment:
      - EDITOR=vim
    volumes:
      - ../rop_rw:/home/llt/rop_rw
      - ../rop_syscall:/home/llt/rop_syscall
      - ../ret2plt:/home/llt/ret2plt
    networks:
        default:

networks:
    default:

