

# This file was *autogenerated* from the file sol.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1024 = Integer(1024); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_7 = Integer(7)
from Crypto.Util.number import getPrime, isPrime, long_to_bytes
from pwn import remote
from sage.all import *

print("Solving discrete log problem")


def gen_sprime():
    n = _sage_const_2 
    while True:
        if n.bit_length() > _sage_const_1024 :
            n = _sage_const_2 
        if n.bit_length() == _sage_const_1024 :
            # print(f"n = {n}")
            if isPrime(n + _sage_const_1 ):
                return n + _sage_const_1 
            else:
                n = _sage_const_2 
        n *= getPrime(_sage_const_10 )


def main():
    p = gen_sprime()
    # p = 120878978987917035062306416450783436793199010617377911266481872285279503153116048084408325359870553562964766483814781426579331948127031143244276158202066802331366148730086478907229026295850695575958518376998463361273723850182149518888749023439811850176645943714187979052782473636378955998560157298975285057787
    # print(f"p = {p}")
    r = remote("10.113.184.121", "10032")
    r.sendlineafter(b"give me a prime:", str(p).encode())
    r.sendlineafter(b"give me a number:", str(_sage_const_7 ).encode())
    ret = r.recvline().decode()
    m = int(ret.lstrip("The hint about my secret:").strip())
    # print(f"m = {m}")

    flag = discrete_log(Mod(m, p), Mod(_sage_const_7 , p))
    # print(f"flag = {flag}")
    print(long_to_bytes(flag))


if __name__ == "__main__":
    main()

