version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    privileged: true
    environment:
      - EDITOR=vim
    volumes:
      - ../StackOverflow:/home/StackOverflow
      - ../ShellCode:/home/ShellCode
    networks:
        default:

networks:
    default:

