version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    privileged: true
    environment:
      - EDITOR=vim
    volumes:
      - ../StackOverflow:/home/llt/StackOverflow
      - ../ShellCode:/home/llt/ShellCode
      - ../GOT:/home/llt/GOT
    networks:
        default:

networks:
    default:

