version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    privileged: true
    ports:
      - "22224:22"
    environment:
      - EDITOR=vim
    volumes:
      - ./share:/home
    networks:
        default:

networks:
    default:

